# Generated by Django 3.2.9 on 2022-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0003_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodcourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=100)),
                ('foodname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('description', models.TextField(max_length=100)),
                ('categoty', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'food_details',
            },
        ),
    ]
