# Generated by Django 3.2.9 on 2022-04-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0004_foodcourt'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcourt',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.merchant'),
            preserve_default=False,
        ),
    ]
