# Generated by Django 3.2.9 on 2022-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0005_foodcourt_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcourt',
            name='hotelname',
        ),
        migrations.AddField(
            model_name='merchant',
            name='hotel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
