# Generated by Django 3.2.9 on 2022-04-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0006_auto_20220407_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcourt',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
