# Generated by Django 3.2.9 on 2022-04-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0007_foodcourt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.CharField(max_length=100)),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('finalcost', models.BigIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.foodcourt')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.merchant')),
            ],
            options={
                'db_table': 'booking_food',
            },
        ),
    ]
