# Generated by Django 3.2.9 on 2022-04-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0008_addcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='add',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
