# Generated by Django 3.2.9 on 2022-04-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0009_addcart_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='customer',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.customer'),
            preserve_default=False,
        ),
    ]
