# Generated by Django 3.2.9 on 2022-04-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0010_addcart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='hotel',
        ),
    ]
