# Generated by Django 3.2.9 on 2022-04-09 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0011_remove_addcart_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='merchant',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.merchant'),
            preserve_default=False,
        ),
    ]
