# Generated by Django 3.2.9 on 2022-04-19 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0014_remove_addcart_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='food',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.foodcourt'),
            preserve_default=False,
        ),
    ]
