# Generated by Django 3.2.9 on 2022-04-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0017_addcart_foods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcart',
            old_name='foods',
            new_name='food',
        ),
    ]
