# Generated by Django 3.2.9 on 2022-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0018_rename_foods_addcart_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='stutus',
            field=models.IntegerField(default=0),
        ),
    ]
