# Generated by Django 3.2.9 on 2022-04-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0019_addcart_stutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='stutus',
        ),
    ]
