# Generated by Django 3.2.9 on 2022-10-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0022_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='img',
            field=models.ImageField(blank=True, default='No Image', upload_to=''),
        ),
    ]
