# Generated by Django 3.2.9 on 2022-10-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0023_alter_merchant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcourt',
            name='image',
            field=models.ImageField(blank=True, default='No Image', upload_to=''),
        ),
    ]
