# Generated by Django 4.0.5 on 2023-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0026_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
