# Generated by Django 4.0.5 on 2023-10-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0027_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
