# Generated by Django 4.0.5 on 2023-10-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0028_alter_address_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='add1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='add2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='pincode',
        ),
    ]
