# Generated by Django 4.0.5 on 2023-10-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0029_rename_add1_address_address_remove_address_add2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='add',
        ),
    ]
