# Generated by Django 4.0.5 on 2023-11-08 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0030_remove_addcart_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mail', models.EmailField(max_length=254)),
                ('quantity', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('address', models.TextField()),
                ('odatetime', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 8, 14, 55, 31, 756100))),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('discount', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('vmail', models.EmailField(max_length=254)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.foodcourt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetfoodapp.order')),
            ],
        ),
    ]
