# Generated by Django 4.0.5 on 2023-11-10 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0031_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 10, 10, 58, 49, 904342)),
        ),
    ]
