# Generated by Django 4.0.5 on 2023-11-10 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfoodapp', '0032_alter_order_odatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odatetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 10, 16, 4, 5, 348866)),
        ),
    ]
